include: all_lint_rules.yaml
analyzer:
  exclude:
    # ignore warnings in files from most generators
    - "**/*.g.dart"
    # ignore lib
    - "lib/dart_midi/**"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    prefer_const_constructors: false
    file_names: false
    sort_pub_dependencies: false
