name: flutter_genshin_lyre
description: A flutter app for genshin lyre tools

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  filepicker_windows: ^2.0.0
  provider: ^5.0.0
  win32: ^2.0.5
  fluent_ui: ^1.4.1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-ExtraLight.ttf
        - asset: fonts/Manrope-Light.ttf
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-Medium.ttf
        - asset: fonts/Manrope-SemiBold.ttf
        - asset: fonts/Manrope-Bold.ttf
        - asset: fonts/Manrope-ExtraBold.ttf
