name: Lint and Test

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  lint-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Cache Flutter dependencies
      #   uses: actions/cache@v1
      #   with:
      #     path: C:\hostedtoolcache\windows\flutter
      #     key: ${{ runner.os }}-flutter-cache
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter analyze
      # - run: flutter test
