name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Cache Flutter dependencies
      #   uses: actions/cache@v1
      #   with:
      #     path: C:\hostedtoolcache\windows\flutter
      #     key: ${{ runner.os }}-flutter-cache
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter analyze
      # - run: flutter test
      - run: flutter build windows
      - run: |
          mv build\windows\runner\release .
          C:\"Program Files"\7-Zip\7z.exe a -tzip genshin_lyre.zip -w release
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            README.md
            LICENSE
            genshin_lyre.zip
